# name: Dependency check builder
# on: 
#   schedule:
#     - cron:  '* 0 * * *' 

# jobs:
#   depcheck-builder:
#     runs-on: ubuntu-latest
#     name: Dependency_check_builder
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Build latest images
#         run: |
#           echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
#           docker build -t ??:latest .
#           docker push ??:latest
